### ISSUE TITLE
AuthenticationError:Unauthorized

### ISSUE THREAD

**Issue by reboy** [chunkai1312/egg-passport-jwt#1]
router.js 文件：

  router.post("/login",app.passport.authenticate('jwt', {session: false, successReturnToOrRedirect: null }))

app.js 文件：
 app.passport.verify(async (ctx, user) => {
        console.log('--------------')
      });

**Comment by chunkai1312** [comment]
@reboy Please check your [token](https://github.com/chunkai1312/egg-passport-jwt#include-the-jwt-in-requests) is valid.

**Comment by reboy** [comment]
thanks，it's ok.
